theme: jekyll-theme-tactile
<section class="fdb-block">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-6 col-lg-3">
        <img alt="image" class="img-fluid" src="./imgs/photos/fireworks-1.jpg">
      </div>

      <div class="col-6 col-lg-3">
        <img alt="image" class="img-fluid" src="./imgs/photos/fireworks-2.jpg">
      </div>

      <div class="col-12 col-lg-6 pt-3">
        <p class="lead text-left">Hola, hola, hola, hello, jajaj, lol, lmao holaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.</p>
        <p class="lead text-left">yes. <a href="https://www.froala.com">[Read More]</a></p>
      </div>
    </div>
  </div>
</section>
